### ISSUE TITLE
filter must handle empty columns more elegantly

### ISSUE THREAD

**Issue by fwhelan** [beiko-lab/ananke#1]
Hi Mike,

Thanks for such a detailed readme on a great resource! I'm working my way through and have encountered an issue with `timeclust filter`:

```
$ timeclust filter -i timeclust_db.h5 -o timeclust_db_filtered.h5 -f abundance -t 100
intializing empty arrays
Data array read!
indices read!
arrays loaded from HDF5 file
Traceback (most recent call last):
  File "/usr/local/bin/timeclust", line 9, in <module>
    load_entry_point('timeclust==0.1.0', 'console_scripts', 'timeclust')()
  File "/usr/local/lib/python2.7/dist-packages/timeclust-0.1.0-py2.7.egg/timeclust/timeclust.py", line 63, in main
    timeseriesdb.filter_data(args.o, float(args.t), args.f)
  File "/usr/local/lib/python2.7/dist-packages/timeclust-0.1.0-py2.7.egg/timeclust/timeclust_database.py", line 215, in filter_data
    new_timeseriesdb.add_names(sample_name_array)
  File "/usr/local/lib/python2.7/dist-packages/timeclust-0.1.0-py2.7.egg/timeclust/timeclust_database.py", line 73, in add_names
    self.h5_table["samples/names"][:] = names_list
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2467)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2424)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 585, in __setitem__
    for fspace in selection.broadcast(mshape):
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/selections.py", line 304, in broadcast
    raise TypeError("Can't broadcast %s -> %s" % (target_shape, count))
TypeError: Can't broadcast (50,) -> (46,)
Closing file
Closing file
```

I get a similar error when I try `-t proportion` or `-t presence`. If I skip `timeclust filter` and try clustering on the unfiltered db, I also encounter an error.

Some details: machine =  x86_64 x86_64 x86_64 GNU/Linux

``````
$less seqs_J.fna
>MPNH21_1572505 MISEQ:138:000000000-ABJYV:1:1101:13566:2229:ATCTCTT orig_bc=ATCTCTT new_bc=ATCTCTT bc_diffs=0
CTGAGGAATATTGGTCAATGGACGGAAGTCTGAACCAGCCAAGTAGCGTGCAGGATGACGGCCCTATGGGTTGTAAACTGCTTTTGTATGGGGATAAAGTTAGGGACGTGTCCCTATTTGCAGGTACCATACGAATAAGGACCGGCTAATTCCGTG
>MPNH21_1572506 MISEQ:138:000000000-ABJYV:1:1101:15965:2244:ATCTCTT orig_bc=ATCTCTT new_bc=ATCTCTT bc_diffs=0
TGAGGAATATTGGTCAATGGGCGAGAGCCTGAACCAGCCAAGTAGCGTGCAGGATGACGGCCCTCCGGGTTGTAAACTGCTTTTAGTTGGGAATAAAAAAAGGGACTTGTCCCTTCTTGTATGTACCTTCAGAGAAAGGACCGGCTAATTCCGTG
>MPNH21_1572507 MISEQ:138:000000000-ABJYV:1:1101:18987:2248:ATCTCTT orig_bc=ATCTCTT new_bc=ATCTCTT bc_diffs=0
TGGGGAATATTGGACAATGGGCGAAAGCCTGATCCAGCCATGCCGCGTGTGTGAAGAAGGTCTTCGGATTGTAAAGCACTTTAAGTTGGGAGGAAGGGCAGTAAGTTAATACCTTGCTGTTTTGACGTTACCAACAGAATAAGCACCGGCTAACTTCGTG
$less map_J.txt
#SampleID       BarcodeSequence LinkerPrimerSequence    Participant     SampleType      time_points         Description
MPNH100 CCGTGCA CCTACGGGAGGCAGCAG       J       E  0       MPNH
MPNH101 CGGCCTT CCTACGGGAGGCAGCAG       J       E  5       MPNH
$ pip show h5py | grep Version
Version: 2.5.0
$ pip show numpy | grep Version
Version: 1.10.4
$ pip show scipy | grep Version
Version: 0.16.1
$ pip show scikit-learn | grep Version
Version: 0.16.1
$ pip show pandas | grep Version
Version: 0.17.1
'```
``````

**Comment by mwhall** [comment]
Interesting. Looks like it is somehow trying to add more sample names than can actually exist. I'll have a look and see if I can reproduce this.

**Comment by fwhelan** [comment]
Just incase others have a similar issue: we discussed offline and found that some of my input FASTA sequences where split across >1 line, breaking the  label\nsequence\n assumption.

**Comment by mwhall** [comment]
Closed with commit: https://github.com/beiko-lab/ananke/commit/851639751945ccb13a0a746e4b1c89663602288d

Empty columns are now properly removed from the file during the `ananke filter` step.
