### ISSUE TITLE
Issue with tabulate

### ISSUE THREAD

**Issue by notlob91** [beiko-lab/ananke#7]
Hi, I'm trying to use Ananke on some time series data I have, but I've run across some issues during the "tabulate" step. Any help would be much appreciated!

**My command:**
`ananke tabulate -i /mnt/maximus/data1/biddle/JGI_mat_amplicon/Raw_Data/FB/rep_set_q29.fna -o FB_ananke_db.h5 -f FB_seq.unique.fasta -m /home/kbousses/ananke-master/mapping_FB.txt -t time_points`

**The error:**

`Traceback (most recent call last):
  File "/home/kbousses/miniconda/bin/ananke", line 11, in <module>
    load_entry_point('ananke==0.3.0', 'console_scripts', 'ananke')()
  File "/home/kbousses/miniconda/lib/python3.4/site-packages/ananke-0.3.0-py3.4.egg/ananke/ananke.py", line 159, in main
    fasta_to_ananke(args.i, args.m, args.t, args.o, args.f, args.multi, args.size_labels)
  File "/home/kbousses/miniconda/lib/python3.4/site-packages/ananke-0.3.0-py3.4.egg/ananke/_tabulate.py", line 238, in fasta_to_ananke
    timeseriesdb = TimeSeriesData(timeseriesdata_path)
  File "/home/kbousses/miniconda/lib/python3.4/site-packages/ananke-0.3.0-py3.4.egg/ananke/_database.py", line 66, in __init__
    maxshape=(None,None), exact=False, fillvalue=-2)
  File "/home/kbousses/miniconda/lib/python3.4/site-packages/h5py/_hl/group.py", line 126, in require_dataset
    return self.create_dataset(name, *(shape, dtype), **kwds)
  File "/home/kbousses/miniconda/lib/python3.4/site-packages/h5py/_hl/group.py", line 105, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/kbousses/miniconda/lib/python3.4/site-packages/h5py/_hl/dataset.py", line 129, in make_new_dset
    dset_id = h5d.create(parent.id, None, tid, sid, dcpl=dcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2696)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2654)
  File "h5py/h5d.pyx", line 79, in h5py.h5d.create (/home/ilan/minonda/conda-bld/work/h5py/h5d.c:1969)
ValueError: Unable to create dataset (No appropriate function for conversion path)
`

**Comment by loulanomics** [comment]
Hi, I am having this same issue. Was this ever resolved? Thank you!

**Comment by ctekellogg** [comment]
I'm also having a similar issue when using ```ananke import_from_dada2``` . Not sure if I have my file structure wrong (since i didn't import directly from dada2 but rather from a phyloseq ASV table generated from dada2 merged and denoised reads in qiime2). 

My data structure for the ASV table is: samples as rows and asv as columns (where the asv name is the sequence). The data structure for the metadata is samples as rows and info, including time_points as columns. My understanding is that the ```-f``` and ```-o``` files are output by ```import_from_dada2``` with the name I give them (at first i thought i had to provide at ```-f``` file but now i gather it is generated by this function.

```
$ ananke import_from_dada2 -i qu39_otus_an
anke.csv -m qu39_metadata_time.txt -t time_points -f seq.unique.dada2.fasta -o 
qu39_ananke.h5
Creating required data sets in new HDF5 file at qu39_ananke.h5
Traceback (most recent call last):
  File "/Users/colleen.kellogg/miniconda2/bin/ananke", line 11, in <module>
    load_entry_point('ananke==0.3.0', 'console_scripts', 'ananke')()
  File "/Users/colleen.kellogg/.local/lib/python2.7/site-packages/ananke-0.3.0-py2.7.egg/ananke/ananke.py", line 161, in main
    dada2_to_ananke(args.i, args.m, args.t, args.o, args.f, args.multi)
  File "/Users/colleen.kellogg/.local/lib/python2.7/site-packages/ananke-0.3.0-py2.7.egg/ananke/_tabulate.py", line 321, in dada2_to_ananke
    timeseriesdb = TimeSeriesData(timeseriesdata_path)
  File "/Users/colleen.kellogg/.local/lib/python2.7/site-packages/ananke-0.3.0-py2.7.egg/ananke/_database.py", line 66, in __init__
    maxshape=(None,None), exact=False, fillvalue=-2)
  File "/Users/colleen.kellogg/miniconda2/lib/python2.7/site-packages/h5py/_hl/group.py", line 191, in require_dataset
    return self.create_dataset(name, *(shape, dtype), **kwds)
  File "/Users/colleen.kellogg/miniconda2/lib/python2.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/Users/colleen.kellogg/miniconda2/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 167, in make_new_dset
    dset_id = h5d.create(parent.id, None, tid, sid, dcpl=dcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 80, in h5py.h5d.create
ValueError: Unable to create dataset (no appropriate function for conversion path)
```

Any help would be so appreciated!

Thank you,
colleen

**Comment by Fmiranda86** [comment]
Same here, have you solved it?

`Creating required data sets in new HDF5 file at ananke_db_0.h5
Traceback (most recent call last):
  File "/home/fmiranda/.local/bin/ananke", line 11, in <module>
    load_entry_point('ananke==0.3.0', 'console_scripts', 'ananke')()
  File "/home/fmiranda/.local/lib/python3.6/site-packages/ananke-0.3.0-py3.6.egg/ananke/ananke.py", line 161, in main
    dada2_to_ananke(args.i, args.m, args.t, args.o, args.f, args.multi)
  File "/home/fmiranda/.local/lib/python3.6/site-packages/ananke-0.3.0-py3.6.egg/ananke/_tabulate.py", line 321, in dada2_to_ananke
    timeseriesdb = TimeSeriesData(timeseriesdata_path)
  File "/home/fmiranda/.local/lib/python3.6/site-packages/ananke-0.3.0-py3.6.egg/ananke/_database.py", line 66, in __init__
    maxshape=(None,None), exact=False, fillvalue=-2)
  File "/home/fmiranda/miniconda3/envs/picrust2/lib/python3.6/site-packages/h5py/_hl/group.py", line 191, in require_dataset
    return self.create_dataset(name, *(shape, dtype), **kwds)
  File "/home/fmiranda/miniconda3/envs/picrust2/lib/python3.6/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/fmiranda/miniconda3/envs/picrust2/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 167, in make_new_dset
    dset_id = h5d.create(parent.id, None, tid, sid, dcpl=dcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 80, in h5py.h5d.create
ValueError: Unable to create dataset (no appropriate function for conversion path)`

Thanks,
Fabi

**Comment by raphenya** [comment]
### Software dependecies used:
```
Package         Version
--------------- -------
ananke          0.3.0  
bitarray        1.2.0  
colorlover      0.3.0  
Cython          0.29.14
h5py            2.10.0 
joblib          0.14.1 
numpy           1.18.0 
paho-mqtt       1.5.0  
pandas          0.25.3 
pip             9.0.1  
pkg-resources   0.0.0  
plotly          4.4.1  
python-dateutil 2.8.1  
pytz            2019.3 
retrying        1.3.3  
scikit-learn    0.22.1 
scipy           1.4.1  
setuptools      39.0.1 
six             1.13.0 
wheel           0.30.0 
```

#### Generated tab / csv file from https://github.com/beiko-lab/ananke/wiki/Importing-Denoised-Sequences-from-DADA2 but only using 16 fastqs

[METADATA_time.txt](https://github.com/beiko-lab/ananke/files/4031924/METADATA_time.txt)

[dada2_export.csv.zip](https://github.com/beiko-lab/ananke/files/4031909/dada2_export.csv.zip)

#### Import command:

```
ananke import_from_dada2 \
-i dada2_export.csv \
-m METADATA_time.txt \
-t time_points \
-f seq.unique.dada2.fasta \
-o mendota_ananke.h5
```

#### Running import command gives:
```
Traceback (most recent call last):
  File "/home/raphenar/h5py/env/bin/ananke", line 11, in <module>
    sys.exit(main())
  File "/home/raphenar/h5py/env/lib/python3.6/site-packages/ananke/ananke.py", line 161, in main
    dada2_to_ananke(args.i, args.m, args.t, args.o, args.f, args.multi)
  File "/home/raphenar/h5py/env/lib/python3.6/site-packages/ananke/_tabulate.py", line 323, in dada2_to_ananke
    timeseriesdb = TimeSeriesData(timeseriesdata_path)
  File "/home/raphenar/h5py/env/lib/python3.6/site-packages/ananke/_database.py", line 78, in __init__
    maxshape=(None,None,), exact=False, fillvalue=-2)	    
  File "/home/raphenar/h5py/env/lib/python3.6/site-packages/h5py/_hl/group.py", line 191, in require_dataset
    return self.create_dataset(name, *(shape, dtype), **kwds)
  File "/home/raphenar/h5py/env/lib/python3.6/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/raphenar/h5py/env/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 167, in make_new_dset
    dset_id = h5d.create(parent.id, None, tid, sid, dcpl=dcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 80, in h5py.h5d.create
ValueError: Unable to create dataset (no appropriate function for conversion path)
```
#### Running ncdump on mendota_ananke.h5 gives: 

```
netcdf mendota_ananke {

// global attributes:
		string :origin_version = "0.3.0" ;

group: genes {
  dimensions:
  	phony_dim_0 = UNLIMITED ; // (1 currently)
  variables:
  	string sequenceclusters(phony_dim_0) ;
  	string sequenceids(phony_dim_0) ;
  	string sequences(phony_dim_0) ;
  	string taxonomy(phony_dim_0) ;
  data:

   sequenceclusters = NIL ;

   sequenceids = NIL ;

   sequences = NIL ;

   taxonomy = NIL ;
  } // group genes

group: timeseries {
  dimensions:
  	phony_dim_1 = UNLIMITED ; // (1 currently)
  variables:
  	int data(phony_dim_1) ;
  	int indices(phony_dim_1) ;
  	int indptr(phony_dim_1) ;
  data:

   data = 0 ;

   indices = 0 ;

   indptr = 0 ;
  } // group timeseries
}
```

- @mwhall @fmaguire It looks like the code is failing at `init` method in the TimeSeriesData class because the `clusters` dataset is not being created (located in the file: https://github.com/beiko-lab/ananke/blob/master/ananke/_database.py)
